Improve error handling in functional tests.

diff --git a/run_functional_tests b/run_functional_tests
--- a/run_functional_tests
+++ b/run_functional_tests
@@ -29,21 +29,22 @@ BAIL_IF_FAILED_TESTS_NOT_FIXED=1
 #make -j parameter
 N_PARALLEL_JOBS=2
 
-server_pid=`./run_server`
+#NailGun server seems to require a kill -9 to exit
+trap 'code=$?; processes="$server_pid $nailgun_server_pid $worker_pids"; ([ "$processes" != "  " ] && kill $processes) || true; ([ -n "$nailgun_server_pid" ] && kill -9 $nailgun_server_pid) || true; exit $code' INT QUIT TERM EXIT
+
+server_pid=`./run_server` || (echo "Could not start Mutinack server" && false)
 echo Started server $server_pid
-nailgun_server_pid=`./run_nailgun_server`
+nailgun_server_pid=`./run_nailgun_server` || (echo "Could not start NailGun server" && false)
 echo Started nailgun server $nailgun_server_pid
 sleep 3
 
 worker_pids=''
 for i in `seq 1 $N_PARALLEL_JOBS`
 do
-	worker_pid=`./run_worker`
+	worker_pid=`./run_worker` || (echo "Could not start Mutinack worker" && false)
 	echo Started worker $worker_pid
 	worker_pids=`echo $worker_pids $worker_pid`
 done
-
-trap 'code=$?; kill $server_pid $nailgun_server_pid $worker_pids || true; exit $code' INT QUIT TERM EXIT
 
 GIT=true
 #Uncomment line below to activate git failed test tracking functionality
@@ -88,7 +89,7 @@ do
 	done
 done
 counter=`expr $counter + 1`
-message="functional tests passed"
+message="Functional tests passed"
 if [ $counter -gt 1 ]
 then
 	message="${message}; WARNING: success only after $counter tries"
